spring:
  application:
    name: pineapple-store
  config:
    import: optional:configserver:http://localhost:8888/
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true

